# Generated by Django 5.2 on 2025-04-06 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_product_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="Description",
            new_name="description",
        ),
    ]
